### ISSUE TITLE
User Login Flow

### ISSUE THREAD

**Issue by okandavut** [okandavut/Otiport#29]
User Login flow:

- Enter the Otiport website.
- After user comes to the site, can see login and register options.
- Click on Input.
- User see Mail and password inputs.
- Enter information (mail and password) and press enter button.
- Log in to the system.

## Todo

- [x] API - Unit Tests of Controller
- [x] API - Implement UI-Controller Layer
- [x] API - Implement Service Layer
- [x] API - Implement Token Provider (JWT) for secure login
- [x] API - Implement Repository Layer
- [x] API - Create Database objects
- [ ] Web Client - Create Container 
- [ ] Web Client - Implement Reducer and actions
- [ ] Web Client - Implement API Layer
- [ ] Web Client - Implement UI Layer
- [ ] Web Client - Unit Tests
