### ISSUE TITLE
Add react-validation package to project

### ISSUE THREAD

**Issue by okandavut** [okandavut/Otiport#36]
Package npm link : https://www.npmjs.com/package/react-validation
## Todo

- [ ] Add react-validation package from NPM or YARN
- [ ] Import package to page
- [ ] Use validations on page
